### PR TITLE
Fixed incorrect behaviour in some games when difficulty ramping was disabled. Default behaviour should not be effected.

### PR DESCRIPTION
**Pull request by ercumentilhan**
Are these conditions meant to work the way I changed them into?

### CODE REVIEW

**Comment by kenjyoung** [comment]
Yes, the alien positioning should be handled correctly by operator precedence (but doesn't hurt to be explicit), but the ramping condition indeed seems incorrect. The same issue also exists in seaquest, could you fix that as well and then I should be able to accept the request.

Thanks for noticing this!

**Comment by ercumentilhan** [comment]
Thanks for reviewing! Done.

**Comment by ondrejba** [comment]
What's the severity of this bug?
I disabled difficulty ramping for some of my experiments, so I'm wondering if they're completely invalid.

**Comment by kenjyoung** [comment]
The games affected are seaquest and asterix. For those games, it looks like the ramping switch was effectively ignored. So the behaviour with ramping disabled will be equivalent to default in those cases. Sorry for the oversight.

**Comment by ondrejba** [comment]
No worries, thanks for the answer!

**Pull request merged**
